add yandex browser
openSUSE/opi pull request #108
Opened 2022-08-04 20:33 UTC by 13werwolf13

due to the fact that yandex-browser is finally out of beta.

2022-08-05 09:13 UTC, asdil12 commented
You have conflicting queries, so this won't work.
Also it would make more sense to put this into a single file (and class) and ask the user, which version they want to install.
Especially as the repo is the same for beta and stable.
See https://github.com/openSUSE/opi/blob/master/opi/plugins/ms_edge.py for an example how this can be done.

2022-08-05 10:02 UTC, 13werwolf13 commented
> You have conflicting queries, so this won't work. Also it would make more sense to put this into a single file (and class) and ask the user, which version they want to install. Especially as the repo is the same for beta and stable. See https://github.com/openSUSE/opi/blob/master/opi/plugins/ms_edge.py for an example how this can be done.

sorry but the repos are NOT the same. However, I understood what to do and will do.
However, I did not understand about the conflict?

2022-08-05 10:06 UTC, asdil12 commented
Oh yea - sorry the repo really seems to be different. But is should still work with a single class. I just don't want to clutter the list of plugins.

About the conflict:
```
queries = ('yandex-browser-stable', 'yandex-browser', 'yandex')
queries = ('yandex-browser-beta', 'yandex-browser', 'yandex')
```
... must not have entries that exist in any other plugin - how should opi otherwise know, which plugin it should run.
I updated the testsuite to check for this case.

2022-08-05 10:15 UTC, 13werwolf13 commented
> ... must not have entries that exist in any other plugin - how should opi otherwise know, which plugin it should run. I updated the testsuite to check for this case.

now I understand. well, I thought that he would give a choice as in a normal text search. i was wrong. I will fix it and send a commit today, but a little later. Thanks.

2022-08-05 14:20 UTC, 13werwolf13 commented
@asdil12 I'm not sure if I did everything right, but I hope so.

2022-08-05 16:02 UTC, asdil12 requested changes
See my comments - also please squash your changes into a single commit and test that everything works.

2022-08-05 16:02 UTC, asdil12 commented on opi/plugins/yandex-browser.py
> +			name = 'option',
```suggestion
			filename = option,
			name = option,
```

2022-08-05 16:02 UTC, asdil12 commented on opi/plugins/yandex-browser.py
> +		opi.ask_keep_repo('yandex-browser')
```suggestion
		opi.install_packages([option])
		opi.ask_keep_repo(option)
```

2022-08-05 16:03 UTC, asdil12 requested changes

2022-08-05 16:03 UTC, asdil12 commented on opi/plugins/yandex-browser.py
> +import subprocess
```suggestion
```

2022-08-05 16:49 UTC, 13werwolf13 commented
@asdil12 sorry, i not know how do that
i do
```
git rebase -i fd4008d7fb53a031a28e25c82b9a023871bcbe84
git push --force
```
and i get
```
Everything up-to-date
```

or should I delete this PR and create a new one from new branch?

2022-08-05 17:07 UTC, 13werwolf13 commented
ah, I figured out how to do it .. fixed.

2022-08-08 08:08 UTC, asdil12 approved these changes

2022-08-08 08:08 UTC, merged