Added gstreamer-plugins-good and -extra to codecs query
openSUSE/opi pull request #46
Opened 2021-04-13 18:55 UTC by VortexAcherontic

Hey there the initial impulse to do this minor change was me as I was messing around with codecs and removed codec packages one by one to reproduce an issue some one else had with his openSUSE install to better guide him to which package he might had missing.

Anyway, after rerunning `opi codecs` to get everything back to normal I did not noticed that gstreamer-plugins-good and [...]-extra was missing and some media on my system failed to play.

Since I did not wanted to create a whole new plugin for this I just added these two packages to the packman plugin and extended the `opi/__init__.py` with a function to allow for just installing packages without the whole install_binary() stuff around it since I felt like this only being a minor change and did not wanted to create too much bloat around this.
Also because packman does not offer [...]-good and [...]-good-extra

If this does not conform with the current state of the project feel free to decline this pull request :)

2021-04-21 14:21 UTC, asdil12 requested changes

2021-04-21 14:21 UTC, asdil12 commented on opi/__init__.py
> +
Could you remove one blank line here

2021-04-21 14:21 UTC, asdil12 commented on opi/plugins/packman.py
> +		opi.install_packages(['gstreamer-plugins-good',
Could you make the formatting analog to the upper one?

```suggestion
		opi.install_packages([
			'gstreamer-plugins-good',
			'gstreamer-plugins-good-extra',
		])   
```

2021-04-30 11:06 UTC, asdil12 commented
To be replaced by https://github.com/openSUSE/opi/pull/50

2021-04-30 11:06 UTC, closed without merging

2021-05-02 11:39 UTC, VortexAcherontic commented
Sorry missed to check my mails ^^"