Install ms edge versions using single plugin
openSUSE/opi pull request #80
Opened 2021-10-29 09:02 UTC by asdil12

Fixes https://github.com/openSUSE/opi/issues/78

2021-11-01 13:35 UTC, giovcandido requested changes
Please, add microsoft-edge-stable to the options list. It's now a thing!

2021-11-01 13:35 UTC, giovcandido commented
By the way, good work!

2021-11-01 13:39 UTC, giovcandido commented
> Testsuite passed locally.

I think you need to update the tests, so they work when you need to choose the package channel (stable, beta, dev).

2021-11-02 04:39 UTC, trmdi commented
Maybe an idea:

Currently there is 2 separated rows for `msedge`, maybe it can be improved like this:
instead of:
> msedge-beta       Microsoft Edge Beta
> msedge-dev        Microsoft Edge Dev

we show:
> msedge-{branch}    Microsoft Edge (branch: beta, dev, stable)

maybe, `opi msedge` will be redirected to the stable branch.

2021-11-15 12:04 UTC, merged